name: Daily Build
on:
  schedule:
    - cron: "0 23 * * *"   # KST 08:00
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python scripts/fetch_weather.py
      - run: python scripts/score.py
      - run: python scripts/build_today.py
      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "chore: daily build $(date -u +%F)" || echo "No changes"
          git push
